# configs/dynunet_config.yaml
model:
  name: "DynUNet"
  spatial_dims: 2
  in_channels: 1
  out_channels: 1

  # DynUNet-specific parameters
  kernel_size: [3, 3, 3, 3]
  strides: [1, 2, 2, 2]
  upsample_kernel_size: [2, 2, 2]
  filters: [32, 64, 128, 256]

  dropout: 0.1
  norm_name: "instance"
  act_name: "leakyrelu"
  deep_supervision: false
  deep_supr_num: 1
  res_block: true
  trans_bias: false
