# configs/unetplusplus_config.yaml
model:
  name: "UNetPlusPlus"
  spatial_dims: 2
  in_channels: 1
  out_channels: 1
  # features sequence controls depth and width
  features: [32, 32, 64, 128, 256]
  norm: "instance"
  deep_supervision: false
