# configs/unet_config.yaml
model:
  name: "UNet"
  spatial_dims: 2
  in_channels: 1   # FLAIR
  out_channels: 1  # segmentation mask
  channels: [32, 64, 128, 256]
  strides: [2, 2, 2, 2]
  num_res_units: 2
  norm: "instance"
